argos-ci/argos

- package.json
- src/config.js
- src/review/index.ejs
- src/review/webpack/browserBaseConfig.js
- src/review/webpack/browserDevelopmentConfig.js
- yarn.lock
> [review] First Hello world

- package.json
- src/review/Routes.js
- src/review/review.js
- src/review/routes/build/Build.js
- src/review/routes/notFound/NotFound.js
- src/review/routes/product/Product.js
- src/review/routes/profile/Profile.js
- src/review/routes/repository/Repository.js
- src/review/routes/settings/Settings.js
- src/review/webpack/browserBaseConfig.js
- src/review/webpack/browserDevelopmentConfig.js
- yarn.lock
react-router v4 is buggy
I'm setting up as simple routes structure, following the travis one.
> [review] Bootstrap the first pages

- package.json
- src/config.js
- src/review/index.ejs
- src/review/routes/build/Build.js
- src/review/routes/build/Screenshots.js
- src/review/routes/build/Summary.js
- src/server/app.js
- src/server/bootstrap/development.js
- src/server/graphql/middleware.js
- src/server/graphql/schema.js
- yarn.lock
Still really really simple.
Next step: fake some data from the server matching our models.
> [Review] Make the first graphql query happen

- src/server/app.js
- src/server/configureDatabase.js
- src/server/graphql/middleware.js
- src/server/models/BaseModel.js
- src/server/models/Build.js
- src/server/models/Organization.js
- src/server/models/Repository.js
- src/server/models/Screenshot.js
- src/server/models/ScreenshotBucket.js
- src/server/models/ScreenshotDiff.js
- src/server/models/User.js
I haven't added the relations between the tables
Next step: create a seed.
> [server] Create the objection models

- knexfile.js
- migrations/20161217154940_init.js
- package.json
- seeds/01_screenshotBuckets.js
- seeds/02_screenshots.js
- seeds/builds.js
- seeds/organizations.js
- seeds/repositories.js
- seeds/screenshotDiffs.js
- seeds/users.js
- src/server/models/ScreenshotBucket.js
- src/server/models/ScreenshotDiff.js
I had to rename the table name to use a `snack_case` convention.
The following code wasn't working otherwise:
```jsx
knex.raw('TRUNCATE screenshot_buckets CASCADE')
```
**Next step**: create a marketing landing page following that great blog post https://medium.com/@cliffordoravec/the-epic-guide-to-bootstrapping-a-saas-startup-from-scratch-by-yourself-part-1-4d834e1df8c1.
> [server] Create a simple seed

- README.md
- src/modules/components/LayoutBody.js
- src/review/routes/product/Argument.js
- src/review/routes/product/Home.js
> [Product] Improve the Home page

- package.json
- src/modules/rxjs/add/operator/debug.js
- src/modules/rxjs/add/operator/watchTask.js
- src/modules/rxjs/operator/debug.js
- src/modules/rxjs/operator/watchTask.js
- src/modules/rxjs/rxjs.js
- src/redux/actionTypes.js
- src/review/Root.js
- src/review/review.js
- src/review/routes/build/Build.js
- src/review/routes/build/epic.js
- src/review/routes/build/reducer.js
- yarn.lock
Step after step, I'm setting up all the layers of the stack to display the screenshots 🎉 
Next step: implement the server graphQL resolver for that query. Data will use the seeds to begin with.
Next step: use the seeds data to actually render something with React.
Related to #25
> [review] Use RxJS to make the request

- src/review/routes/build/epic.js
- src/server/graphql/BuildType.js
- src/server/graphql/ScreenshotBucketType.js
- src/server/graphql/middleware.js
- src/server/graphql/schema.js
- src/server/models/Build.js
- src/server/models/Organization.js
- src/server/models/Repository.js
- src/server/models/Screenshot.js
- src/server/models/ScreenshotBucket.js
- src/server/models/ScreenshotDiff.js
- src/server/models/User.js
Next step: go deeper in the graph tree, we need to access the `screenshot_diffs`:
> [review] Implement the build resolver

- src/server/graphql/BuildType.js
- src/server/graphql/ScreenshotBucketType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/ScreenshotType.js
- src/server/graphql/middleware.js
- src/server/graphql/schema.js
- src/server/models/Screenshot.js
- src/server/models/ScreenshotDiff.js
> [review] Increase the graphql knowledge

- knexfile.js
- src/modules/imageDiff/multipleDiffs.test.js
- src/server/routes/api.js
- src/server/routes/api.test.js
- src/server/testUtils.js
> feat(api): add get buckets API

- package.json
- src/modules/crashReporter/crashReporter.js
- src/review/review.js
- src/review/webpack/browserBaseConfig.js
- src/review/webpack/browserProductionConfig.js
- src/server/routes/app.js
- yarn.lock
- https://sentry.io/argos/argos-server/
- https://sentry.io/argos/argos-browser/
> feat(js): track errors in production

- src/config.js
- src/modules/crashReporter/crashReporter.js
- src/server/middlewares/rendering.js
Also added a hook in sentry.
- https://devcenter.heroku.com/articles/dyno-metadata
> chore: track releases in sentry

- .eslintignore
- .gitignore
- README.md
- package.json
- packages/argos-cli/package.json
- packages/argos-cli/src/upload.test.js
- packages/argos-cli/yarn.lock
```
08:16:34 (use-argos) ~/doctolib$ npm run argos
> doctolib@0.448.0 argos /Users/oliviertassinari/doctolib
> argos upload tmp/screenshots --token $ARGOS_TOKEN
module.js:472
throw err;
^
Error: Cannot find module 'convict'
```
> fix(client): add missing convict dependency

- package.json
- src/modules/graphQL/GraphQLDateTime.js
- src/server/graphql/BuildType.js
- src/server/graphql/ScreenshotBucketType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/ScreenshotType.js
Throwing warning, the lib is unmaintained.
> fix(yarn): remove a crappy dependency

- package.json
- src/modules/build/computeScreenshotDiff.js
- src/modules/s3/upload.js
> feat: upload diff to s3

- src/review/routes/product/Home.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/schema.js
- src/server/models/Build.js
- src/server/models/Build.test.js
- src/server/routes/api.js
- src/server/routes/api.test.js
- src/server/routes/www.test.js
> feat(review): sort the diffs by score desc

- src/modules/jobs/createJob.js
> chore: stronger jobs

- src/modules/build/computeScreenshotDiff.test.js
- src/modules/build/createBuildDiffs.test.js
- src/modules/synchronizer/GitHubSynchronizer.test.js
- src/modules/synchronizer/synchronize.test.js
- src/server/routes/api.test.js
- src/server/routes/www.test.js
- src/server/test/factory.js
- src/server/test/utils.js
https://github.com/aexmachina/factory-girl
Closes #97
> chore(js): use factory-girl

- src/review/routes/build/BuildScreenshotItem.js
- src/review/routes/build/BuildScreenshots.js
- src/review/routes/build/epic.js
- src/server/graphql/ScreenshotDiffType.js
> feat(review): display the diff in the UI

- migrations/20170222222346_add_jobStatus_to_builds.js
- package.json
- src/modules/build/computeScreenshotDiff.js
- src/modules/build/computeScreenshotDiff.test.js
- src/modules/build/createBuildDiffs.js
- src/modules/build/createBuildDiffs.test.js
- src/modules/jobs/createJob.js
- src/modules/jobs/createModelJob.js
- src/modules/synchronizer/GitHubSynchronizer.js
- src/modules/synchronizer/GitHubSynchronizer.test.js
- src/modules/synchronizer/synchronize.js
- src/modules/synchronizer/synchronize.test.js
- src/server/jobs/build.js
- src/server/jobs/screenshotDiff.js
- src/server/jobs/synchronize.js
- src/server/models/Build.js
- src/server/models/Build.test.js
- src/server/models/ScreenshotDiff.js
- src/server/models/Synchronization.js
- src/server/routes/api.js
- src/server/routes/configurePassport.js
- src/server/test/factory.js
- yarn.lock
> refactor(jobs): make it generic and notify errors

- src/modules/crashReporter/crashReporter.js
Try to minimize code branch between the production and the development env.
Following https://github.com/getsentry/raven-node/blob/master/lib/client.js#L91 and https://github.com/getsentry/raven-node/pull/15
Closes #118.
> fix(sentry): disable in dev mode

- src/modules/crashReporter/crashReporter.js
- src/modules/jobs/createJob.js
> chore(jobs): log context when an error occurs

- src/modules/build/computeScreenshotDiff.js
- src/modules/build/computeScreenshotDiff.test.js
- src/server/models/ScreenshotDiff.js
> feat: avoid uploading screenshot if score === 0

- .travis.yml
- config/test.json
- knexfile.js
- src/modules/build/notifyStatus.js
- src/modules/build/notifyStatus.test.js
- src/modules/urls/buildUrl.js
- src/modules/urls/buildUrl.test.js
- src/server/models/Organization.js
- src/server/models/Organization.test.js
- src/server/models/Repository.js
- src/server/models/Repository.test.js
- src/server/models/User.js
- src/server/models/User.test.js
- src/server/test/factory.js
- src/server/test/utils.js
Closes #105
Also dramatically speed up test by using delete instead of truncate (x4 speed up).
> feat: notify with build url

- packages/argos-cli/src/index.js
- src/server/routes/api.js
> fix(upload): allow more screenshots in the input

- src/modules/crashReporter/crashReporter.js
- src/modules/jobs/reduceJobStatus.test.js
- src/review/Routes.js
- src/review/modules/components/ItemStatus.js
- src/review/routes/build/BuildScreenshotItem.js
- src/review/routes/build/BuildSummary.js
- src/review/routes/build/BuildSummary.test.js
- src/review/routes/build/epic.js
- src/review/routes/repository/RepositoryDetails.js
- src/review/routes/repository/RepositoryDetailsItem.js
- src/review/routes/repository/detailsEpic.js
- src/server/graphql/BuildType.js
- src/server/graphql/OrganizationType.js
- src/server/graphql/RepositoryType.js
- src/server/graphql/ScreenshotBucketType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/ScreenshotType.js
- src/server/routes/www.test.js
Closes #125 
Then, I'm going to work on #59.
> feat(review): more visual feedback on the status

- db/structure.sql
- migrations/20170304184220_add_constraints.js
- migrations/20170304184221_remove_constraints.js
- src/server/test/factory.js
Already ran in production
Closes #94
> chore(database): consolidate db constraints

- db/structure.sql
- migrations/20170306205356_new-notifications.js
- src/modules/build/notifications.js
- src/review/routes/build/buildEpic.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/middleware.js
- src/server/graphql/middleware.test.js
- src/server/graphql/schema.js
- src/server/models/Build.js
- src/server/models/BuildNotification.js
For instance https://api.github.com/repos/callemall/material-ui/statuses/8fcaca081dcf18815b474d68b3c4952f4adc83cb?access_token=084fc8f8dfaf25386ed5c1b12cdb9eff4ff735e7.
The next step for #59 is to display the status correctly.
> feat(review): send the review down to github

- src/server/routes/app.js
> chore: redirect from http to https

- Procfile
- package.json
- yarn.lock
Closes #159
https://github.com/nodejs/node/issues/3370
> chore: fix V8 memory on heroku

- src/modules/build/computeScreenshotDiff.test.js
- src/modules/build/createBuildDiffs.js
- src/modules/build/createBuildDiffs.test.js
- src/modules/build/notifications.js
- src/review/routes/build/BuildActions.js
- src/review/routes/build/BuildSummary.js
- src/review/routes/build/buildEpic.js
- src/server/graphql/BuildType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/middleware.test.js
- src/server/models/Build.js
- src/server/models/Build.test.js
- src/server/models/ScreenshotDiff.js
- src/server/models/ScreenshotDiff.test.js
- src/server/models/constant.js
- src/server/test/factory.js
> feat: finish the validation action

- src/server/graphql/BuildType.js
- src/server/graphql/RepositoryType.js
- src/server/graphql/ScreenshotBucketType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/ScreenshotType.js
> core(graphql): restrict the type of an id, only a string

- src/server/graphql/OwnerType.js
- src/server/graphql/middleware.test.js
> fix(profile): fix user profile

- config/production.json
- package.json
- src/config.js
- src/modules/crashReporter/crashReporter.js
- src/modules/graphQL/client.js
- src/review/review.js
- src/review/webpack/browserBaseConfig.js
- src/server/bootstrap/nodeEnvTest.js
- src/server/bootstrap/setup.js
- src/server/bootstrap/setupTest.js
- src/server/graphql/middleware.js
- src/server/middlewares/rendering.js
- src/server/routes/app.js
- yarn.lock
> chore(sentry): setup sentry on GraphQL requests

- .travis.yml
- package.json
- packages/argos-cli/package.json
- packages/argos-cli/src/index.js
- packages/argos-cli/src/setupRaven.js
- packages/argos-cli/test/setupEnv.js
- packages/argos-cli/yarn.lock
- src/server/bootstrap/nodeEnvTest.js
> chore(sentry): enable sentry on client

- README.md
- seeds/04_screenshots.js
- seeds/screenshotDiffs.js
- src/review/routes/profile/Profile.js
- src/server/graphql/BuildType.js
- src/server/graphql/middleware.test.js
> fix(review): small tweeks

- src/modules/graphQL/client.js
- src/review/webpack/browserBaseConfig.js
- src/server/middlewares/rendering.js
> chore: read release version from clientData

- db/structure.sql
- knexfile.js
- migrations/20170319114827_add_github_scopes_to_users.js
- src/modules/authorizations/authorizationStatuses.js
- src/modules/authorizations/checkAuthorization.js
- src/modules/authorizations/getAuthorizationStatus.js
- src/modules/authorizations/getUserAuthorizationState.js
- src/modules/authorizations/scopes.js
- src/modules/build/notifications.js
- src/modules/synchronizer/GitHubSynchronizer.js
- src/review/modules/components/AuthorizationNotice.js
- src/review/routes/dashboard/Dashboard.js
- src/server/middlewares/rendering.js
- src/server/models/User.js
- src/server/routes/configurePassport.js
> fix: handle authorization correctly

- src/review/modules/components/AuthorizationNotice.js
- src/server/routes/app.js
- src/server/routes/www.js
> feat(server): expose the public folder for all the subdomains

- src/modules/components/WatchTask.js
- src/modules/rxjs/operator/watchTask.js
- src/modules/s3/download.test.js
- src/modules/s3/upload.test.js
- src/review/routes/repository/RepositoryDetails.js
- src/review/routes/repository/RepositoryDetailsLoadMore.js
- src/review/routes/repository/detailsActions.js
- src/review/routes/repository/detailsEpic.js
- src/review/routes/repository/detailsReducer.js
- src/review/routes/repository/detailsReducer.test.js
- src/server/models/Build.test.js
- src/server/models/ScreenshotBucket.test.js
- src/server/routes/api.test.js
- yarn.lock
> feat(review): add a load more button

- src/modules/authorizations/getUserAuthorizationState.test.js
- src/server/models/ScreenshotBucket.js
- src/server/models/ScreenshotBucket.test.js
> feat(model): new validation on the commit

- src/review/index.ejs
- src/review/routes/product/Home.js
Following travis example that is describing the action instead of the outcome.
> feat(seo): small tweak

- src/server/routes/api.js
- src/server/routes/api.test.js
- src/server/routes/app.test.js
That was such a pain in the ass!
> fix(server): correct status logic

- README.md
- db/structure.sql
- migrations/20170329213934_allow_null_baseScreenshotIds.js
- package.json
- src/modules/baseCompare/baseCompare.js
- src/modules/baseCompare/baseCompare.test.js
- src/modules/build/createBuildDiffs.js
- src/modules/build/createBuildDiffs.test.js
- src/modules/build/notifications.js
- src/review/routes/build/BuildScreenshotItem.js
- src/review/routes/build/BuildScreenshotItem.test.js
- src/review/routes/build/BuildSummary.js
- src/review/routes/build/BuildSummary.test.js
- src/review/routes/build/BuildSummaryBody.js
- src/review/routes/build/BuildSummaryBody.test.js
- src/server/bootstrap/setupTest.js
- src/server/graphql/BuildType.js
- src/server/graphql/middleware.test.js
- src/server/jobs/build.js
- src/server/jobs/build.test.js
- src/server/jobs/screenshotDiff.js
- src/server/models/Build.js
- src/server/models/ScreenshotDiff.js
- src/server/routes/api.js
- src/server/routes/app.test.js
- test/fixtures/baseCompare.json
- test/fixtures/baseCompareMaster.json
- yarn.lock
Start working on #232 as well as #188 also improving the fallbackToMaster logic and the `/builds` response time.
Missing:
Target: https://github.com/argos-ci/argos/milestone/4 🎉
> feat(build): support the first build

- package.json
- src/review/routes/Error.js
- src/review/routes/homepage/Homepage.js
- src/server/middlewares/errorHandler.js
- src/server/middlewares/rendering.js
- src/server/routes/api.js
- src/server/routes/app.js
- src/server/routes/www.js
- yarn.lock
Closes #242 
Message and stack trace are not displayed in production.
> chore: improve error handler

- src/server/routes/configurePassport.js
> chore: report login errors

- db/structure.sql
- migrations/20170402203440_repository_baseline_branch.js
- seeds/02_repositories.js
- src/modules/baseCompare/baseCompare.js
- src/modules/build/createBuildDiffs.js
- src/modules/synchronizer/GitHubSynchronizer.js
- src/server/models/Repository.js
- src/server/test/factory.js
> feat(diff): add a baselineBranch option

- src/modules/build/createBuildDiffs.js
- src/modules/build/createBuildDiffs.test.js
- src/server/jobs/build.js
- src/server/jobs/build.test.js
> feat(diff): ignore the baselineBranch

- src/review/routes/build/BuildActions.js
- src/review/routes/build/BuildSummary.js
- src/review/routes/build/buildEpic.js
- src/server/graphql/BuildType.js
- src/server/graphql/RepositoryType.js
- src/server/graphql/ScreenshotDiffType.js
- src/server/graphql/utils.js
Fix https://sentry.io/argos/argos-server/issues/245565677/
> fix(review): take the user write authorization into account

- .eslintrc.js
- package.json
- src/modules/baseCompare/baseCompare.js
- src/review/routes/build/BuildSummaryBody.js
- src/review/routes/build/BuildSummaryBody.test.js
- src/review/routes/build/buildEpic.js
- src/server/bootstrap/consoleError.js
- src/server/bootstrap/setupTest.js
- yarn.lock
> feat(review): link the build summary with Github

- src/server/models/Repository.js
- src/server/routes/api.js
- src/server/routes/app.test.js
> feat(name): take into account the names

- src/modules/components/Link.js
- src/modules/components/WatchTask.js
- src/review/routes/build/Build.js
- src/review/routes/dashboard/Dashboard.js
- src/review/routes/profile/Account.js
- src/review/routes/profile/Profile.js
- src/review/routes/repository/Repository.js
- src/review/routes/repository/RepositoryDetails.js
- src/review/routes/repository/repositoryEpic.js
- src/server/graphql/BuildType.js
- src/server/graphql/RepositoryType.js
- src/server/graphql/utils.js
- src/server/models/Repository.js
We are leaking the token of Material-UI and Argos-CI, not good 😬 .
> fix(back): security issue

- ci/test.sh
- package.json
- yarn.lock
```
=== argos-cli: uploading 'screenshots/sample' directory...
i  identified `travis` environment
i  using `fix-ci-detection` as branch
i  using `52bb790f96d97ea1bf33a1b3f92068b1236db089` as commit
i  found 6 screenshots to upload
✔  Upload complete!
build created id: 3716
```
> fix: ci-detection

- nodemon.json
- src/review/routes/build/Build.spec.js
- src/review/routes/settings/Settings.js
- src/review/routes/settings/Settings.spec.js
> fix(review): hide the content when no right

- examples/with-happo/.eslintrc.js
- examples/with-happo/.happo.js
- examples/with-nightmare/.eslintrc.js
- examples/with-vrtest/.eslintrc.js
- examples/with-wdio/.eslintrc.js
- examples/with-wdio/wdio.conf.js
- src/modules/build/notifications.js
- src/modules/components/ReviewFooter.js
- src/modules/crashReporter/index.js
- src/modules/graphql/client.js
- src/modules/urls/buildUrl.js
- src/modules/urls/buildUrl.test.js
- src/server/middlewares/rendering.js
- src/server/routes/api.js
- src/server/routes/app.test.js
- src/server/test/utils.js
> feat(build): display the build url

- src/server/bootstrap/setupTest.js
- src/server/graphql/middleware.test.js
- src/server/test/utils.js
Show meaningful information when breaking the tests.
> test(graphql): add a noGraphqlErrors util

- .eslintrc.js
- examples/with-storybook/.babelrc
- examples/with-storybook/.gitignore
- examples/with-storybook/.happo.js
- examples/with-storybook/README.md
- examples/with-storybook/package.json
- examples/with-storybook/stories/Button.js
- examples/with-storybook/storybook/config.js
- examples/with-storybook/test/normalize.js
- examples/with-storybook/test/tests.js
- examples/with-storybook/test/webpack.config.js
Porting https://github.com/algolia/react-instantsearch/pull/130 back here.
> docs(with-storybook): add a new integration example

- .env.example
- apps/app/src/containers/AppNavbar.js
- apps/app/src/pages/Repository/BuildDetail/index.js
Resolve https://github.com/argos-ci/argos/issues/424
> fix: hide approved when no permission

- Procfile
Process screenshots in parallel
> x3 more workers

- apps/config/src/index.js
- apps/synchronize/src/github/synchronizer.js
- fix: fix installation not found
- fix: fix number of database connections
> various fixes

- package.json
- yarn.lock
Ignore SSL errors
https://github.com/probot/smee.io/issues/39#issuecomment-657205742
> chore: fix smee client

- apps/synchronize/src/github/synchronizer.js
When transfering a repository from a user -> org or org -> user.
> fix(sync): fix sync bug

- .gitignore
- apps/app/src/App.js
- apps/app/src/components/Link.js
- apps/app/src/components/Sidebar.js
- apps/app/src/containers/Theme.js
- apps/app/src/pages/NotFound.js
- apps/app/src/pages/Owner/GeneralSettings.js
- apps/app/src/pages/Owner/PermissionsSettings.js
- apps/app/src/pages/Owner/Settings.js
- apps/app/src/pages/Owner/index.js
- apps/app/src/pages/Repository/BuildDetail/Screenshots.js
- apps/config/environments/production.json
- apps/config/src/index.js
- apps/graphql/src/definitions/Owner.js
- apps/graphql/src/definitions/Plan.js
- apps/graphql/src/definitions/Purchase.js
- apps/graphql/src/definitions/index.js
- apps/web/src/middlewares/rendering.js
> feat: add account consumption

- apps/app/package.json
- package-lock.json
> Revert "fix: fix missing moment dep in app"

- apps/app/src/components/Card.js
- apps/app/src/components/Code.js
- apps/app/src/pages/Repository/RepositoryContext.js
- apps/app/src/pages/Repository/Settings.js
- apps/graphql/src/definitions/Repository.js
> feat: updatable base branch

- apps/web/src/api/v2/builds/update.js
> fix: fix concurrent upload

- apps/app/src/pages/Repository/Builds.js
> fix(builds): do not display getting started with no user

- apps/build-notification/src/notifications.test.js
- apps/build/src/baseCompare.js
- apps/job-core/src/createJob.js
> fix(sentry): notify only after retry

- apps/app/src/containers/Apollo.js
- apps/app/src/containers/Breadcrumb/OwnerBreadcrumb.js
- apps/app/src/containers/Breadcrumb/OwnerBreadcrumbMenu.js
- apps/app/src/pages/ErrorPage.js
- apps/app/src/pages/Home.js
- apps/app/src/pages/Owner/OwnerSettings.js
- apps/app/src/pages/Owner/Repositories.js
fixes ARGOS-BROWSER-3X
fixes 3554264367
> fix: set apollo owner possible types

- apps/synchronize/src/github/synchronizer.js
fixes ARG-98
fixes ARGOS-SERVER-XDZ
> feat: catch unknown installation id error

- apps/build-notification/src/notifications.js
- apps/job-core/src/createJob.js
> fix: ignore notifications error

- apps/build/src/baseCompare.js
- apps/database/src/testing/factory.js
A wrong bucket was picked because the name was ignored.
> fix(build): fix wrong bucket choice

- apps/app/src/containers/AppNavbar.js
- apps/app/src/pages/AuthCallback.js
> feat(login): redirect after login

- apps/build-notification/src/notifications.js
> fix: fix no commit found for SHA error

- apps/app/src/components/Tooltip.js
- apps/app/src/components/index.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/index.js
- feat(build): remove duplicate screenshots
- feat(build): add build stats tooltips
> build tooltip

- apps/app/src/components/Table.js
- apps/app/src/pages/Repository/Builds.js
> feat: improve build list

- apps/app/src/containers/Status.js
- apps/app/src/pages/Build/ScreenshotDiffStatusIcons.js
- apps/app/src/pages/Build/index.js
- apps/graphql/src/definitions/Build.js
- apps/graphql/src/definitions/ScreenshotDiff.js
> feat: add failed screenshot diffs status

- apps/app/src/components/Menu.js
- apps/app/src/pages/Build/UpdateStatusButton.js
- feat(menu): update menu caret
- feat(build): add caret to review button
> review button

- apps/app/src/pages/Build/ScreenshotDiffsSection.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/StableScreenshotDiffs.js
- apps/app/src/pages/Build/index.js
- apps/app/src/pages/Home.js
- refactor(build): add stable build section file
- feat(build): screenshot diffs lazy image mounting
> screenshot diff lazy mounting

- apps/app/src/pages/Build/SummaryCard.js
- apps/database/db/structure.sql
- apps/database/migrations/20220912221410_add_build_parallel_total.js
- apps/database/src/models/Build.js
- apps/graphql/src/definitions/Build.js
- apps/web/src/api/v2/builds/update.js
- apps/web/src/app.api-v2.test.js
> feat(build): display parallel build progression

- apps/build/src/createBuildDiffs.js
- apps/build/src/createBuildDiffs.test.js
> feat(build): set build type

- apps/app/src/containers/BuildStatusBadge.js
- apps/app/src/containers/Status.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
- apps/app/src/pages/Home.js
- apps/app/src/pages/Repository/Builds.js
- apps/database/src/models/Build.js
- apps/database/src/models/Build.test.js
- apps/graphql/src/definitions/Build.js
> feat(build): add build expired status

- apps/app/src/pages/Build/index.js
> feat(build): polling pending build data

- apps/app/src/containers/Status.js
- apps/database/seeds/seeds.js
> test(seeds): add all builds status

- apps/app/src/pages/Home.js
> feat: improve missing installation page

- apps/database/migrations/20220918153730_add_old_build_type.js
> fix(build-status): fix old build statuses

- apps/database/db/structure.sql
- apps/database/migrations/20220918102241_fix_accounts_only_one_non_null_constraint.js
- apps/database/src/testing/factory.js
- apps/synchronize/src/github/marketplaceEvents/change.test.js
- apps/synchronize/src/github/marketplaceEvents/pendingChange.test.js
- apps/synchronize/src/github/marketplaceEvents/pendingChangeCancel.test.js
- apps/synchronize/src/github/marketplaceEvents/purchase.test.js
> fix(db): fix account unique owner contraint

- apps/app/src/containers/Breadcrumb/OwnerBreadcrumb.js
> feat: add owner breadcrumb default icon

- apps/app/src/pages/NotFound.js
- apps/app/src/pages/Repository/Builds.js
- apps/app/src/pages/Repository/index.js
- apps/graphql/src/definitions/Owner.js
> fix(404): fix 404 page

- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
> fix(sticky-menu): fix blink on page loading

- apps/app/src/components/Code.js
- apps/app/src/components/CollapseCard.js
- apps/app/src/components/Theme.js
- apps/app/src/components/index.js
- apps/app/src/containers/Status.js
- apps/app/src/pages/Build/BuildStatusInfo.js
- apps/app/src/pages/Build/ReviewButton.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
- apps/app/src/pages/Repository/Builds.js
- apps/app/src/pages/Repository/GettingStarted.js
- apps/graphql/src/definitions/Repository.js
Fixes ARG-118 ARG-117 ARG-116 ARG-114
- feat(build): add build status info card
- feat(build): hide review button when useless
> build status info

- apps/app/src/components/Button.js
- apps/app/src/components/Menu.js
- apps/app/src/pages/Build/ReviewButton.js
- apps/app/src/pages/Build/index.js
- apps/app/webpack.config.js
- apps/database/seeds/seeds.js
- apps/database/src/models/Account.js
- apps/database/src/models/Account.test.js
- apps/database/src/models/Plan.js
- apps/database/src/models/Repository.js
- apps/graphql/src/definitions/Build.js
- apps/graphql/src/definitions/Owner.js
- apps/graphql/src/definitions/Repository.js
- apps/graphql/src/definitions/User.js
- apps/web/src/api/v2/builds/create.js
- apps/web/src/middlewares/repoAuth.js
- apps/web/src/middlewares/repoAuth.test.js
Resolves ARG-52 
- feat(build): add overcapacity banner
- feat(build): disable review button for overcapacity private repo
> feat(build): add plan limit banner

- apps/synchronize/src/github/synchronizer.js
> chore: fix update purchase

- examples/circleci/.circleci/config.yml
- examples/circleci/.gitignore
- examples/cypress/.gitignore
- examples/github-actions/.github/workflows/ci.yml
- examples/github-actions/.gitignore
- examples/playwright/.gitignore
- examples/travis/.gitignore
- examples/travis/.travis.yml
- examples/webdriver-io/.gitignore
- examples/webdriver-io/README.md
- examples/webdriver-io/package.json
- examples/webdriver-io/test/specs/example.e2e.js
- examples/webdriver-io/wdio.conf.js
- doc(examples): udpate gitignore files
- doc(example): add webdriverIO example
> webdriverIO example

- apps/graphql/src/definitions/Owner.js
- apps/graphql/src/definitions/User.js
> fix(settings): fallback owner name to login

- apps/app/src/components/Theme.js
- apps/app/src/pages/Build/ReviewButton.js
- apps/app/src/pages/Build/ScreenshotDiffsSection.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
> feat: display diff on two columns

- apps/database/src/models/Repository.js
- apps/web/src/middlewares/repoAuth.js
- apps/web/src/middlewares/repoAuth.test.js
- apps/web/src/middlewares/tokenless-strategies/github-actions.js
> feat: add github actions tokenless strategy

- apps/app/src/containers/BuildStatusBadge.js
- apps/app/src/containers/Status.js
- apps/app/src/pages/Build/BuildStatusInfo.js
- apps/build/src/createBuildDiffs.js
- apps/build/src/createBuildDiffs.test.js
> fix(build): prevent missing build type

- apps/database/db/structure.sql
- apps/database/migrations/20221013113904_add_forced_plan.js
- apps/database/src/models/Account.js
- apps/database/src/models/Account.test.js
> feat: add account forced plan

- .gitignore
- apps/app/src/components/Loader.js
- apps/app/src/components/Time.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Repository/Builds.js
- tests/utils.js
Before : <img width="362" alt="Capture d’écran 2022-10-17 à 00 19 03" src="https://user-images.githubusercontent.com/15954562/196061063-626fba34-09a9-4c44-a6e2-9286904886a1.png">
After : <img width="446" alt="Capture d’écran 2022-10-17 à 00 18 46" src="https://user-images.githubusercontent.com/15954562/196061078-bba03ec2-6cb0-4a4d-8667-a2065315a0d0.png">
> fix: sticky approve menu

- .storybook/preview.js
- apps/app/src/App.js
- apps/app/src/components/Button.js
- apps/app/src/components/GlobalStyle.js
- apps/app/src/components/Input.js
- apps/app/src/components/Menu.js
- apps/app/src/components/Theme.js
- apps/app/src/components/ToggleGroupButtons.js
- apps/app/src/containers/AppNavbar.js
- apps/app/src/containers/Layout.js
- apps/app/src/containers/Status.js
- apps/app/src/pages/Build/ScreenshotsDiffCard.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
- apps/app/src/pages/Home.js
- stories/Button.stories.js
- feat: add color modes
- feat: remove 'background' color
- feat: rework button
> rework button

- apps/app/src/components/Theme.js
- apps/app/src/pages/Build/NewBuild.js
- feat(new-build): remove organization link
- feat: rework chip colors
> rework chip color

- apps/app/src/components/BuildStat.js
- apps/app/src/components/ThumbnailsList.js
- apps/app/src/components/index.js
- apps/app/src/pages/Build/BuildSidebar.js
- apps/app/src/pages/Build/index.js
This PR improve the thumbnail list with this features :
- Show empty cells to remove display blinks
- Add build stats before with link to scroll in the list
> feat(thumbnails-list): add build stats

- apps/app/src/components/BuildStat.js
- apps/app/src/components/Code.js
- apps/app/src/components/Theme.js
- apps/app/src/components/ThumbnailsList.js
- apps/app/src/components/Tooltip.js
- apps/app/src/containers/BuildStatusChip.js
- apps/app/src/pages/Build/BuildDiff.js
- apps/app/src/pages/Build/BuildStatusInfo.js
- apps/app/src/pages/Build/NewBuild.js
- apps/app/src/pages/Build/ReviewButton.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Build/index.js
- apps/app/src/pages/Home.js
- apps/app/src/pages/Repository/Builds.js
- feat: rework tooltip
- feat: add paragraph tooltip
- feat: add tootip to BuildStatusChip
> rework tootip

- apps/app/src/pages/Build/BuildDiff.js
> feat(new-build): missing screenshot alerts

- apps/app/src/components/BuildStat.js
- apps/app/src/components/Code.js
- apps/app/src/pages/Build/BuildDiff.js
- apps/app/src/pages/Build/Hotkeys.js
- apps/app/src/pages/Build/NewBuild.js
- apps/app/src/pages/Build/ReviewButton.js
- fix: review button tooltip message
- fix: tooltip message case
- feat(new-build): contained screenshots
- feat(new-build): toggle screenshots size
> feat(new-build): toggle screenshots size

- apps/app/src/pages/ModernBuild/BuildDiffState.tsx
- apps/app/src/pages/ModernBuild/BuildPage.tsx
- apps/database/seeds/seeds.js
- apps/graphql/src/definitions/Screenshot.ts
- apps/graphql/src/definitions/ScreenshotDiff.ts
- apps/graphql/src/loaders.ts
- test: add seed of diff with variable height
- feat: add width and height to screenshot graphql
> variable thumbnail image sizes

- apps/app/src/pages/ModernBuild/BuildDetailToolbar.tsx
- apps/app/src/pages/ModernBuild/BuildDiffList.tsx
- tests/build.spec.js
I tried the css aspect-ratio props but it didn't do anything so I have removed it.
> feat: use screenshot size in list

- apps/app/src/modern/ui/Dialog.tsx
- apps/app/src/modern/ui/Tooltip.tsx
- fix: inscrease tooltip zIndex
- fix: inscrease dialog zIndex
> fix tooltip z index

- apps/app/src/App.js
- apps/app/src/index.css
- apps/app/src/modern/ui/HotkeyTooltip.tsx
- apps/app/src/modern/ui/Kbd.tsx
- apps/app/src/modern/ui/Tooltip.tsx
- apps/app/src/pages/ModernBuild/BuildDetail.tsx
- apps/app/src/pages/ModernBuild/BuildDetailToolbar.tsx
- apps/app/src/pages/ModernBuild/BuildDiffList.tsx
- apps/app/src/pages/ModernBuild/BuildHotkeys.tsx
- apps/app/src/pages/ModernBuild/BuildPage.tsx
- apps/app/src/pages/ModernBuild/BuildSidebar.tsx
- apps/app/src/pages/ModernBuild/BuildStatsIndicator.tsx
- apps/app/src/pages/ModernBuild/BuildWorkspace.tsx
- feat(build): opacify diff
- refactor(tooltip): remove provider
- feat(modern): implements tooltips + hotkeys
> build improvements

- apps/database/src/models/Build.test.ts
- apps/database/src/models/Build.ts
- apps/graphql/src/loaders.ts
> perf: better build status algo

- apps/database/db/structure.sql
- apps/database/migrations/20221123165000_add_indexes.js
> add indexes

- apps/app/src/modern/containers/Build.tsx
> fix: expired status chip

- apps/app/src/pages/ModernBuild/BuildDetail.tsx
> feat: improve failure screenshot description

- apps/github/src/client.ts
> fix: handle suspended installation

- apps/build/src/createBuildDiffs.ts
- apps/web/src/api/v2/builds/update.ts
Fix ARGOS-SERVER-XFT
https://stackoverflow.com/a/67770840
> fix: no empty insert

- apps/synchronize/src/github/synchronizer.ts
> fix: handle suspended user

- apps/web/src/redis/index.ts
> fix(redis): fix socket closed

- apps/app/src/pages/Build/BuildDetail.tsx
- apps/app/src/ui/Code.tsx
> feat: display branch name on a single line

- .github/workflows/ci.yml
- apps/build-notification/src/notifications.ts
- apps/database/src/models/Build.ts
- apps/database/src/models/ScreenshotDiff.ts
- apps/graphql/src/definitions/Build.ts
- apps/graphql/src/definitions/ScreenshotDiff.ts
- feat: diff-detected pending on GitHub
- refactor: move stats logic to model
- feat: improve notification message
> diff detected pending

- apps/database/db/structure.sql
- apps/database/migrations/20230103095309_add_pr_number.js
- apps/database/src/models/Build.ts
- apps/web/src/api/v2/builds/create.ts
> feat: store prNumber

- apps/screenshot-diff/src/computeScreenshotDiff.ts
- apps/storage/src/ImageFile.ts
It does not work really well, it has to be done client-side.
> fix: remove preload

- apps/app/src/pages/Build/BuildDetail.tsx
- apps/app/src/pages/Build/BuildDetailToolbar.tsx
- apps/app/src/pages/Build/BuildDiffShowBaselineState.tsx
- apps/app/src/pages/Build/BuildHotkeys.tsx
- apps/app/src/ui/ColumnsIcon.tsx
> feat: toogle baseline column

- examples/github-actions/.github/workflows/ci.yml
@slorber reported a problem in the example
> docs: update GitHub Actions example

- apps/build-notification/src/notifications.ts
- apps/build/src/baseCompare.ts
- apps/build/src/createBuildDiffs.ts
- apps/job-core/src/createJob.ts
- apps/job-core/src/error.ts
- apps/job-core/src/index.ts
Fix #729
- In one request to GitHub we got the accurate "merge base"
- When we can't found a complete bucket for a merge base, the build is now "orphan"
> fix: better merge base strategy

- CONTRIBUTING.md
- Procfile.dev
- apps/app/package.json
- apps/build-notification/package.json
- apps/build/package.json
- apps/capture/package.json
- apps/config/package.json
- apps/crawl/package.json
- apps/database/package.json
- apps/github/package.json
- apps/graphql/package.json
- apps/job-core/package.json
- apps/logger/package.json
- apps/processes/package.json
- apps/processes/turbo.json
- apps/screenshot-diff/package.json
- apps/sentry-node/package.json
- apps/storage/package.json
- apps/synchronize/package.json
- apps/web/package.json
- package-lock.json
- package.json
- turbo.json
`npm run procfile` is no longer needed, only `npm run dev`.
> chore: only one command to start project

- Procfile
- apps/capture/src/job.ts
- apps/config/src/index.ts
- apps/database/src/knex.ts
- apps/job-core/src/amqp.ts
- apps/processes/package.json
- apps/processes/src/bin/build-and-synchronize.ts
- apps/processes/src/bin/crawl-and-capture.ts
- apps/processes/src/bin/screenshot-diff.ts
- apps/processes/src/bin/web.ts
- apps/processes/src/proc/web.ts
- apps/web/src/redis/index.ts
- playwright.config.mjs
Remove bin processes, remove SIGTERM handling, fix .env
> chore: fix dev

- apps/github/package.json
- apps/github/src/client.ts
- package-lock.json
> fix(github): fix error while calling GitHub

- apps/database/src/models/GithubRepository.ts
- apps/job-core/src/createJob.ts
- apps/synchronize/src/synchronizer.ts
- refactor: simplify builder
- chore(job): error logging isolation
- fix(sync): do not insert empty array
> fix job isolation

- apps/app/src/containers/Navbar.tsx
- apps/app/src/containers/ProjectList.tsx
- apps/database/src/models/Account.ts
- chore: remove debug
- refactor(projects): unify buttons
- feat(user): review user menu dropdown
> 776 fix add project link in user menu dropdown

- apps/app/src/containers/GitHub.tsx
- apps/app/src/containers/LoginButtons.tsx
- apps/app/src/pages/Invite.tsx
- apps/app/src/pages/Login.tsx
- apps/app/src/pages/Vercel.tsx
- apps/graphql/src/definitions/Team.ts
Also refactor login everywhere.
Closes #784
> feat(team): custom login on invite page

- apps/app/src/gql/graphql.ts
- apps/database/db/structure.sql
- apps/database/migrations/20230505112219_add_purchase_payment_method_filled.js
- apps/database/src/models/Purchase.ts
- apps/database/src/testing/factory.ts
- apps/graphql/src/__generated__/resolver-types.ts
- apps/graphql/src/definitions/Purchase.ts
fix https://github.com/argos-ci/argos/issues/822
> feat: add payment method filled field

- apps/app/src/containers/LoginButtons.tsx
- apps/app/src/pages/Account/Settings.tsx
- apps/app/src/ui/StripePortalLink.tsx
- apps/config/src/index.ts
- apps/web/src/middlewares/rendering.ts
FIX [#821](https://github.com/argos-ci/argos/issues/821)
- feat: remove empty consumption from details
- feat: rename settings page
- feat: improve personnal settings plan
> rework personal settings

- apps/build/src/base.ts
> fix: fix wrong result without commit

- apps/app/src/containers/ReviewButton.tsx
- apps/graphql/src/definitions/Build.ts
> feat: remove build review limitation

- apps/database/src/models/Account.ts
- apps/database/src/models/Purchase.ts
- apps/graphql/src/definitions/Purchase.ts
> feat: prevent usage-based pricing during trial

- apps/app/src/containers/PaymentBanner.tsx
- apps/app/src/containers/UpgradeDialog.tsx
- apps/app/src/ui/StripeLink.tsx
- feat: improve upgrade dialog button style
- fix: stipe portal access
> fix stripe portal link

- apps/app/src/containers/Auth.tsx
> feat: redirect after logout

- apps/app/src/pages/AuthCallback.tsx
> fix(login): fix redirect at first login

- apps/graphql/src/definitions/Team.ts
> fix(team): correctly sort members

- apps/build-notification/src/notifications.ts
- apps/build/src/base.ts
- apps/build/src/createBuildDiffs.ts
- apps/database/db/structure.sql
- apps/database/migrations/20230524074946_build-reference.js
- apps/database/src/models/Build.ts
- apps/web/src/api/v2/builds/create.ts
- apps/web/src/api/v2/util.ts
> feat: support project not linked to GitHub

- apps/web/src/api/auth.ts
- fix(auth): fix auth with GitHub
- refactor(auth): explicit method name
- fix(auth): do not overload name & slug from GitHub at login
> fix auth with github

- apps/build/src/job.ts
- apps/web/src/api/v2/util.ts
- apps/web/src/app.api-v2.test.ts
SHOULD BE MERGED **AFTER** NEW PLAN RELEASE
fix #838
> Enforce Pro plan for team build creation

- apps/graphql/src/services/project.ts
> fix(delete): fix delete project

- apps/app/src/containers/Team/Members.tsx
- apps/app/src/ui/Form.tsx
- apps/graphql/src/definitions/Team.ts
- feat(team): show message when last user of team
- fix(team): make the last user owner
> handle last team user

- apps/app/src/containers/Team/Members.tsx
> fix(team): fix remove member layout

- apps/app/src/pages/Build/BuildDetail.tsx
> feat(build): improve empty build

- apps/database/src/services/screenshots.ts
> fix(upload): prevent uploading screenshots with the same name

- apps/app/src/App.tsx
- apps/app/src/pages/Project/index.tsx
> feat: remove tests page

- apps/database/src/models/Account.ts
- apps/database/src/models/Team.ts
- apps/database/src/models/User.ts
- apps/database/src/services/account.ts
- apps/database/src/services/team.ts
- apps/graphql/src/definitions/Team.ts
- apps/logger/src/index.ts
- apps/synchronize/package.json
- apps/synchronize/src/fixtures/purchase-event-payload.ts
- apps/synchronize/src/github/eventHelpers.test.ts
- apps/synchronize/src/github/eventHelpers.ts
- apps/synchronize/src/github/events.ts
- apps/web/src/api/auth.ts
- package-lock.json
> fix(purchase): handle purchase from GitHub Marketplace

- apps/database/db/structure.sql
- apps/database/migrations/20230703200439_test-name-length.js
- apps/database/src/models/Build.ts
- apps/database/src/models/Screenshot.ts
- apps/database/src/models/Test.ts
Maximum filename is 256 chars, so we allow 4 folder nested with maximum characters. Should be enough.
Fix ARGOS-SERVER-XJ1
> fix(tests): allow test name of 1024 characters

- apps/graphql/src/services/project.ts
Delete build notifications before deleting builds
> fix(project): fix delete project

- apps/database/src/services/account.ts
- apps/synchronize/src/github/eventHelpers.ts
- apps/web/src/api/auth.ts
> feat(github): ask user email

- apps/app/src/pages/Build/BuildDetail.tsx
- apps/app/src/pages/Build/BuildDiffList.tsx
Closes #938
Related to https://github.com/mui/material-ui/pull/37939#issuecomment-1632961761
> feat(build): enable loseless compression

- apps/screenshot-diff/src/util/image-diff/index.ts
Closes https://github.com/argos-ci/argos/issues/940
Related to https://github.com/mui/material-ui/pull/37939#issuecomment-1632961761
> feat(diff): improve diff algo for small images

- apps/app/src/pages/Build/BuildDetail.tsx
- apps/app/src/pages/Build/BuildDetailToolbar.tsx
- apps/app/src/pages/Build/BuildStatsIndicator.tsx
- apps/app/src/pages/Build/Zoomer.tsx
- apps/app/src/ui/Button.tsx
- apps/app/src/ui/IconButton.tsx
- apps/app/src/ui/Menu.tsx
- apps/app/src/ui/Select.tsx
- Add controls (zoom in, zoom out, fit)
- Figma like controls
- Expand now directly in the view
> feat(zoom): improve it

- apps/app/package.json
- apps/app/src/pages/Build/BuildDetailToolbar.tsx
- apps/app/src/pages/Build/BuildDiffList.tsx
- apps/app/src/pages/Build/BuildDiffState.tsx
- apps/app/src/pages/Build/BuildHotkeys.tsx
- apps/app/src/pages/Build/BuildSidebar.tsx
- package-lock.json
Closes #971
- Icon to toggle search
- Shortcut CMD + F
- If a search is already made, keep it
- If a search is already made and the user active search, select previous one
- ArrowDown & ArrowUp to navigate between results
- Highlight search matching
- Fuzzy search, works with space, accents, etc..
> feat(build): search

- apps/app/src/containers/Auth.tsx
> feat: set token expiration to 60 days

- apps/build-notification/src/notifications.ts
> fix: fix error catching

- apps/build/src/createBuildDiffs.ts
- apps/database/src/models/Project.ts
> fix: handle no reference branch

- apps/app/src/containers/Redirect.tsx
- apps/app/src/pages/AuthCallback.tsx
> feat(gitlab): support deny to login

- apps/app/src/containers/Auth.tsx
- apps/app/src/containers/Layout.tsx
- apps/app/src/containers/Team/Members.tsx
- apps/app/src/containers/Vercel/ProjectsSummary.tsx
- apps/app/src/ui/StripeLink.tsx
Some errors popped because the user clicked in the UI without being actually logged in. We handled that properly now by redirecting him to the login page without notifying Sentry.
> better auth handling

- apps/app/src/containers/Account/GitLab.tsx
- apps/app/src/containers/Project/ReferenceBranch.tsx
- apps/app/src/ui/FormCardFooter.tsx
- fix: remove dot from link
- fix: fix all card form footers
- feat: add link to ref branch doc
> reference branch

- apps/app/src/containers/Account/ChangeSlug.tsx
- apps/database/src/models/Account.ts
> feat: improve account slug validation regexp

- apps/app/src/pages/ErrorPage.tsx
> fix: error page typo

- apps/frontend/src/containers/Team/Members.tsx
> fix(team): fix remove user from team

- .env.example
- apps/backend/package.json
- apps/backend/src/config/index.ts
- apps/backend/src/database/models/Account.ts
- apps/backend/src/web/api/auth.ts
- apps/backend/src/web/api/v2/index.ts
- apps/backend/src/web/vercel.ts
- apps/frontend/src/containers/Account/ChangeSlug.tsx
- package-lock.json
- chore: add rate limiter
- chore(regexp): fix dangerous regexp
- chore: avoid sending unsecure payload
- chore: invalidate stripe test key
> security fixes

- apps/backend/db/migrations/20231024085955_fix-github-account-type-constraint.js
- apps/backend/db/structure.sql
- apps/backend/src/graphql/definitions/GithubPullRequest.ts
> fix(db): fix github account type constraint

- apps/backend/src/screenshot-diff/computeScreenshotDiff.ts
- apps/backend/src/util/chunk.ts
- perf(diff): improve perf
- perf(diff): simplify query
> perf screenshot diff

- apps/frontend/src/pages/Account/index.tsx
> refactor: avoid using Query in Account

- apps/backend/src/graphql/definitions/Account.ts
> fix: fix account update

- apps/backend/src/database/models/Account.ts
- apps/frontend/src/containers/PlanCard.tsx
- fix: fix period start date mutation
- feat: display year in period if not the same year
> 1128 bug fix consumption start date display

- apps/backend/src/graphql/apollo.ts
- apps/backend/src/graphql/definitions/Build.ts
- apps/backend/src/graphql/definitions/Team.ts
- apps/backend/src/graphql/util.ts
- apps/frontend/src/containers/Team/Members.tsx
Fix ARGOS-BROWSER-6R
Fix ARGOS-SERVER-XKN
> fix: handle leave team error

- apps/backend/src/build-notification/aggregated.e2e.test.ts
- apps/backend/src/build-notification/aggregated.ts
> fix(summary): fix build aggregation

- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
> fix: tokenless naming conflict

- apps/backend/src/build/createBuildDiffs.ts
Failures happening on reference build was counted as removed screenshots in subsequent diffs. It's not really a screenshot removal, so we avoid doing that.
I also refactored a bit:
- Find reference branch outside the transaction
- Use `invariant` to avoid `!` operator
> fix: do not mark failures as removed screenshot

- apps/backend/src/database/models/Purchase.ts
- apps/backend/src/graphql/__generated__/resolver-types.ts
- apps/backend/src/graphql/definitions/Account.ts
- apps/backend/src/graphql/definitions/Team.ts
- apps/backend/src/graphql/services/account.ts
- apps/backend/src/stripe/index.ts
- apps/backend/src/synchronize/github/updatePurchase.ts
- apps/backend/src/web/api/stripe.ts
- apps/frontend/src/containers/Team/Delete.tsx
- apps/frontend/src/gql/graphql.ts
- fix(stripe): add `accountId` and `purchaseId` to new Stripe subscriptions
- fix(stripe): avoid swallowing stripe errors
- feat: update delete team wording
- fix: cancel Stripe subscription when account is deleted
> Fix Stripe stuff

- apps/backend/package.json
- apps/backend/src/graphql/definitions/Account.ts
- apps/frontend/package.json
- apps/frontend/src/pages/Account/NewProject.tsx
- apps/frontend/src/pages/Account/Projects.tsx
- apps/frontend/src/util/invariant.ts
- knip.json
- package-lock.json
- chore(dev): delay watch-server
- chore: update `@apollo/client`
- fix: update projects when a new project is created
- feat(projects): sort projects by most recently created project or build
> various fixes 2

- apps/backend/src/build/base.ts
- apps/backend/src/build/baseQuery.e2e.test.ts
- apps/backend/src/build/baseQuery.ts
- apps/backend/src/build/createBuildDiffs.ts
- apps/backend/src/database/models/Project.ts
Also improve perf by minimizing the transaction process.
> feat: support reference build triggered from PR

- apps/backend/src/util/redis/lock.ts
- Prevent memory leak by breaking Promise chaining
- Add random delay between retries to avoid clashing
- Set a random value and check it to avoid to be removed by another
client
- Crash if process is longer than timeout
> fix(lock): improve redis lock algo

- apps/backend/db/migrations/20240222154748_not-nullable-payment-method-filled.js
- apps/backend/db/structure.sql
- apps/backend/src/database/models/Subscription.ts
- apps/backend/src/synchronize/github/events.ts
> fix: make `paymentMethodFilled` non nullable

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- **refactor: refactor image stuff**
- **refactor: refactor download button**
> refacto images

- apps/backend/src/build-notification/aggregated.e2e.test.ts
- apps/backend/src/build-notification/notification.ts
- apps/backend/src/build-notification/utils.ts
- apps/backend/src/build/job.e2e.test.ts
- apps/backend/src/build/job.ts
- apps/backend/src/database/models/Build.ts
- apps/backend/src/database/models/ScreenshotDiff.ts
- apps/backend/src/screenshot-diff/computeScreenshotDiff.ts
Added and removed screenshots on a build are now considered as a
difference and requires an approval.
> feat: consider added & removed as diff

- apps/backend/src/graphql/definitions/GlApiProject.ts
> fix(gitlab): handle "Not found" error

- apps/backend/src/stripe/index.ts
- apps/backend/src/web/api/builds.ts
- apps/backend/src/web/api/stripe.ts
- apps/backend/src/web/api/v2/builds/create.ts
- apps/backend/src/web/api/v2/builds/update.ts
- apps/backend/src/web/api/v2/util.ts
- apps/backend/src/web/middlewares/bearerAuth.ts
- apps/backend/src/web/middlewares/repoAuth.ts
- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
- apps/backend/src/web/middlewares/validate.ts
- apps/backend/src/web/util.ts
- **fix(stripe): fix customer updated**
- **refactor: replace HttpError by a typed one with cause support**
> fix stripe events handler

- apps/backend/src/web/app.ts
- package.json
- scripts/release.sh
- **chore: remove sentry release code**
- **chore: remove deprecation**
- **chore: rename root package**
> remove sentry release code

- apps/backend/src/build/base.ts
- apps/backend/src/build/createBuildDiffs.e2e.test.ts
- apps/backend/src/build/job.e2e.test.ts
I want a Sentry for now to know if we have some customers impacted by that.
> fix: handle missing repo install

- apps/backend/src/util/redis/index.ts
> fix(redis): ignore some errors

- apps/backend/src/job-core/createJob.ts
> fix(amqp): fix channel closed

- apps/backend/src/gitlab/client.ts
- turbo.json
- **chore(turbo): opt out experimental ui**
- **fix(gitlab): handle not found error properly**
> fix gitlab error

- apps/backend/src/github-pull-request/pullRequest.ts
- apps/backend/src/github/comment.ts
> fix(pull-request): handle not found pull-request

- apps/backend/src/email/send.ts
Fix ARGOS-SERVER-XNK
Fix ARGOS-SERVER-XNM
Fix ARGOS-BROWSER-7C
> fix(resend): be tolerant to email failures

- apps/frontend/src/App.tsx
- apps/frontend/src/containers/Auth.tsx
- apps/frontend/src/containers/Breadcrumb/AccountBreadcrumb.tsx
- apps/frontend/src/containers/Breadcrumb/AccountBreadcrumbMenu.tsx
- apps/frontend/src/containers/Breadcrumb/ProjectBreadcrumbMenu.tsx
- apps/frontend/src/containers/Layout.tsx
- apps/frontend/src/containers/NavUserControl.tsx
- apps/frontend/src/containers/SubNavbar.tsx
- apps/frontend/src/pages/Account/NewProject.tsx
- apps/frontend/src/pages/Account/Projects.tsx
- apps/frontend/src/pages/Account/Settings.tsx
- apps/frontend/src/pages/Account/index.tsx
- apps/frontend/src/pages/AuthCallback.tsx
- apps/frontend/src/pages/Build/BuildWorkspace.tsx
- apps/frontend/src/pages/Build/header/BuildHeader.tsx
- apps/frontend/src/pages/Build/index.tsx
- apps/frontend/src/pages/Home.tsx
- apps/frontend/src/pages/Invite.tsx
- apps/frontend/src/pages/Login.tsx
- apps/frontend/src/pages/NewProject.tsx
- apps/frontend/src/pages/NewTeam.tsx
- apps/frontend/src/pages/Project/Builds.tsx
- apps/frontend/src/pages/Project/Reference.tsx
- apps/frontend/src/pages/Project/Settings.tsx
- apps/frontend/src/pages/Project/index.tsx
- apps/frontend/src/pages/Signup.tsx
- apps/frontend/vite.config.ts
- package.json
Also improve CLS on build page
> perf: use suspense + lazy load routes

- apps/backend/src/build-notification/comment.ts
- apps/frontend/src/pages/Build/BuildDiffGroup.tsx
- **feat(build): use meaningful colors for added/removed/retried-failure**
- **fix(comment): use warning for change detected**
> meaningful

- apps/backend/src/slack/index.ts
- apps/frontend/src/containers/Team/Slack.tsx
- **fix(slack): no screenshots section if no stats**
- **fix(slack): display button only for admins**
> minor fixes slack

- apps/backend/src/graphql/definitions/Account.ts
- apps/backend/src/graphql/services/account.ts
- apps/backend/src/graphql/services/project.ts
- apps/backend/src/slack/index.ts
- apps/backend/src/stripe/index.ts
Handle account with a Slack installation
> feat(account): delete account in a transaction

- apps/frontend/src/containers/AccountHistory.tsx
- apps/frontend/src/containers/NavUserControl.tsx
- apps/frontend/src/containers/PullRequestButton.tsx
- apps/frontend/src/pages/Account/index.tsx
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/pages/Build/BuildSidebar.tsx
- apps/frontend/src/pages/Build/BuildStatsIndicator.tsx
- apps/frontend/src/pages/Build/header/BuildHeader.tsx
- apps/frontend/src/pages/Project/Builds.tsx
- apps/frontend/src/pages/Project/index.tsx
- apps/frontend/src/ui/IconButton.tsx
- apps/frontend/src/ui/Link.tsx
- apps/frontend/src/ui/List.tsx
- apps/frontend/src/ui/ListBox.tsx
- apps/frontend/src/ui/Menu.tsx
- apps/frontend/src/ui/TabLink.tsx
- apps/frontend/src/ui/Truncable.tsx
- apps/frontend/tailwind.config.js
- **fix: fix tablink issue with ids**
- **fix: various fixes around React Aria**
> Fix tabs & other React Aria stuff

- apps/backend/src/build/strategy/strategies/ci/index.ts
- apps/backend/src/build/strategy/strategies/ci/strategies/github.ts
- apps/backend/src/build/strategy/strategies/ci/strategies/gitlab.ts
> refactor: fetch database deps locally

- apps/frontend/src/containers/PlanCard.tsx
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/pages/Build/BuildHotkeys.tsx
- apps/frontend/src/pages/Build/BuildOrphanDialog.tsx
- apps/frontend/src/pages/Build/toolbar/ViewToggle.tsx
- apps/frontend/src/ui/CopyButton.tsx
- apps/frontend/src/ui/Dialog.tsx
- apps/frontend/src/ui/HotkeyTooltip.tsx
- apps/frontend/src/ui/Modal.tsx
Also improve shortcuts dialog.
> feat: change shortcut for baseline/changes

- apps/backend/src/build/strategy/strategies/ci/strategies/github.ts
- apps/backend/src/synchronize/synchronizer.ts
> fix: fix GitHub uninstall

- apps/backend/package.json
- apps/backend/src/util/rate-limit.ts
- apps/backend/src/util/redis/index.ts
- apps/backend/src/web/api/v2/index.ts
- apps/backend/src/web/app-router.ts
- docker-compose.yml
- package-lock.json
- Rate limit the whole app
- Use Redis to support multiple nodes
> feat: improve rate limiting

- apps/frontend/src/containers/GitHub.tsx
- apps/frontend/src/containers/GithubInstallationsSelect.tsx
- apps/frontend/src/containers/GithubRepositoryList.tsx
- apps/frontend/src/ui/Link.tsx
- **fix: fix link target**
- **feat: handle missing repo in the list**
> handle missing repo

- apps/backend/db/migrations/20240614204320_build_shards.js
- apps/backend/db/structure.sql
- apps/backend/package.json
- apps/backend/src/build-notification/notifications.ts
- apps/backend/src/build/partial.ts
- apps/backend/src/database/models/Build.ts
- apps/backend/src/database/models/BuildShard.ts
- apps/backend/src/database/models/Screenshot.ts
- apps/backend/src/database/models/index.ts
- apps/backend/src/database/services/screenshots.ts
- apps/backend/src/github/client.ts
- apps/backend/src/github/comment.ts
- apps/backend/src/synchronize/github/events.ts
- apps/backend/src/web/api/v2/builds/create.ts
- apps/backend/src/web/api/v2/builds/update.ts
- apps/backend/src/web/api/v2/util.ts
- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
- package-lock.json
- We collect informations on the build: `runId` and `runAttempt`.
- We determine if it's a partial build or not. To determine that, we look at the jobs of the run, if two are similar in terms of date, then it's a partial retry.
- If it's a partial build, then we will finish this build when the run will be completed (we listen the GitHub webhook).
> feat: support GitHub Actions partial retries

- apps/backend/db/migrations/20240616142430_build_shards_indices.js
- apps/backend/db/structure.sql
- apps/backend/src/build/partial.ts
- apps/frontend/src/pages/Build/BuildWorkspace.tsx
- **fix: fix typo plural**
- **fix(partial): copy shard**
- **fix(partial): add missing indices**
> add missing indices

- apps/backend/src/synchronize/github/updateSubscription.ts
> fix(github): fix subscription update from marketplace

- apps/frontend/src/util/color-detection/worker.ts
Make it work with fingerprinting blocker (like the built-in one in Brave browser)
> fix(highlighter): fix compatibility with fingerprinting blocker

- apps/backend/package.json
- apps/backend/src/build-notification/notifications.ts
- apps/backend/src/build/partial.ts
- apps/backend/src/build/strategy/strategies/ci/strategies/github.ts
- apps/backend/src/database/models/ScreenshotBucket.test.ts
- apps/backend/src/github-pull-request/pullRequest.ts
- apps/backend/src/github/client.ts
- apps/backend/src/github/comment.ts
- apps/backend/src/job-core/createJob.ts
- apps/backend/src/storage/checkIfExists.ts
- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
- package-lock.json
> fix: fix partial check

- apps/backend/package.json
- apps/backend/src/build-notification/notifications.ts
- apps/backend/src/build/partial.ts
- apps/backend/src/build/strategy/strategies/ci/strategies/github.ts
- apps/backend/src/github-pull-request/pullRequest.ts
- apps/backend/src/github/client.ts
- apps/backend/src/github/comment.ts
- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
- package-lock.json
Fix ARGOS-SERVER-XNQ
Fix ARGOS-SERVER-XP7
Fix ARGOS-SERVER-XPB
> fix: fix octokit error detection

- apps/backend/src/build-notification/notifications.ts
- apps/backend/src/github/comment.ts
- apps/backend/src/screenshot-diff/computeScreenshotDiff.ts
- apps/backend/src/util/redis/lock.e2e.test.ts
- apps/backend/src/util/redis/lock.ts
- apps/backend/src/web/api/v2/builds/create.ts
- apps/backend/src/web/api/v2/builds/update.ts
- apps/backend/src/web/api/v2/util.ts
Also refactor lock to accept an array
Fix ARGOS-SERVER-XMC
> fix: avoid concurrent gh commit status creation

- apps/backend/src/api/handlers/updateBuild.ts
- apps/frontend/src/containers/BuildStatusDescription.tsx
- apps/frontend/src/pages/Build/BuildWorkspace.tsx
- **fix: fix finalize**
- **feat: display parallel progress**
> fix parallel progress

- apps/backend/src/graphql/apollo.ts
- apps/backend/src/graphql/services/account.ts
> fix: fix team delete deadlock

- apps/backend/src/api/util.ts
> fix: increase api limit

- apps/backend/src/database/services/account.ts
> fix: handle update email

- apps/backend/src/google/auth.ts
- apps/backend/src/web/app-router.ts
> fix: fix invalid redirect

- apps/frontend/src/pages/Build/metadata/TestIndicator.tsx
> fix: fix test indicator link

- apps/backend/src/email/express.tsx
- apps/backend/src/email/welcome.tsx
path.join does not work for URLs
> fix: fix logo url in email

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/BuildDetailToolbar.tsx
- **fix: fix overlay visibility**
- **feat: reorganize toolbar, do not show overlay if not applicable**
> reorganize toolbar

- apps/backend/src/build/partial.ts
> fix: fix empty query

- apps/backend/src/web/app.ts
> fix: fix CSP for GitLab images

- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/pages/Build/BuildDiffState.tsx
- apps/frontend/src/pages/Build/BuildReviewState.tsx
- apps/frontend/src/pages/Build/toolbar/TrackButtons.tsx
- apps/frontend/src/ui/Popover.tsx
- apps/frontend/src/ui/Tooltip.tsx
- Fix bug where a finalized review could lead to inconsistent state
- Collapse items that are reviewed
- Move to the next item to review once an item has been reviewed
> feat(review): optimize review experience

- apps/frontend/src/pages/Build/BuildDiffColorState.tsx
- apps/frontend/src/ui/TwicPicture.tsx
- **fix: fix diff overlay positionning**
- **fix: display original image, not altered**
> fix various rendering bugs

- apps/frontend/src/ui/Menu.tsx
> fix: horizontal scrollbar

- apps/frontend/src/containers/GitHub.tsx
- apps/frontend/src/containers/GitLab.tsx
- apps/frontend/src/containers/GithubInstallationsSelect.tsx
- apps/frontend/src/containers/GithubRepositoryList.tsx
- apps/frontend/src/containers/Google.tsx
- apps/frontend/src/containers/Project/ConnectRepository.tsx
- apps/frontend/src/containers/Team/GitHubLight.tsx
- apps/frontend/src/containers/Team/GitHubSSO/Configure.tsx
- apps/frontend/src/containers/User/providers/GitHubAuth.tsx
- apps/frontend/src/containers/User/providers/GitLabAuth.tsx
- apps/frontend/src/containers/User/providers/GoogleAuth.tsx
- apps/frontend/src/util/oauth.ts
Fix ARGOS-BROWSER-9Y
Fix ARGOS-BROWSER-9X
> fix: fix oauth URL

- apps/backend/src/database/services/account.ts
> fix: fix concurrency in github account members creation

- apps/frontend/src/router.tsx
> fix: reload if failed to fetch

- apps/backend/src/web/app.ts
> fix: allow Gravatar in CSP

- apps/frontend/src/pages/AuthCallback.tsx
Fix ARGOS-BROWSER-A8
Fix ARGOS-BROWSER-AB
> fix(auth): redirect if invalid callback

- apps/backend/src/config/index.ts
- apps/backend/src/graceful/shutdown.ts
- apps/backend/src/graphql/definitions/Project.ts
- apps/backend/src/processes/proc/build-and-synchronize.ts
- apps/backend/src/processes/proc/screenshot-diff.ts
- apps/backend/src/processes/proc/web.ts
- apps/backend/src/processes/setup.ts
- apps/backend/src/sentry/index.ts
- apps/backend/src/web/app.ts
- apps/frontend/src/containers/Layout.tsx
- apps/frontend/src/index.tsx
- apps/frontend/src/router.tsx
By default we will not report CSP, we can activate it on demand by adding an URL into environment variables.
> chore: improve Sentry CSP setup

- apps/backend/src/github/comment.ts
To investigate ARGOS-SERVER-XPK
> chore: improve error log

- apps/backend/src/database/services/account.ts
> fix: fix `getOrCreateGhAccount` concurrency

- apps/backend/src/web/api/auth.ts
- apps/backend/src/web/app-router.ts
- apps/backend/src/web/app.ts
- apps/backend/src/web/middlewares/github.ts
- apps/backend/src/web/util.ts
> chore: various improvements on server

- apps/backend/src/web/app-router.ts
> chore: fix stream is not readable

- apps/backend/src/web/app-router.ts
> chore: respond 400 for request not readable

- apps/backend/src/database/services/account.ts
- apps/frontend/src/util/api.ts
- **fix: fix auth from GitHub with some slugs**
- **chore: improve error API message**
> Fix auth GitHub slug

- apps/frontend/src/router.tsx
> feat(firefox): automatically reload page if module not found

- apps/frontend/src/containers/Breadcrumb/ProjectBreadcrumbMenu.tsx
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/pages/Build/BuildDiffState.tsx
- apps/frontend/src/pages/Build/BuildSidebar.tsx
- apps/frontend/src/pages/Build/toolbar/FitToggle.tsx
- apps/frontend/src/pages/Build/toolbar/TrackButtons.tsx
- apps/frontend/src/pages/Build/toolbar/ViewToggle.tsx
- **fix: fix project breadcrumbs menu loading**
- **feat: improve responsiveness of search**
- **feat: put some `startTransition` to improve the UI responsiveness**
> enhance ui

- apps/frontend/src/util/oauth.ts
Keep the nonce in the localStorage to avoid any regenerated one.
Fix ARGOS-BROWSER-9X
> fix: fix auth issue

- apps/frontend/src/containers/Apollo.tsx
> feat: retry apollo queries

- apps/frontend/src/router.tsx
> feat: support Safari for dynamic import loading failure

- apps/backend/src/build/strategy/strategies/ci/strategies/github.ts
> chore: retry GitHub merge base request

- apps/backend/package.json
- eslint.config.mjs
- packages/knex-scripts/.swcrc
- packages/knex-scripts/bin/knex-scripts.js
- packages/knex-scripts/package.json
- packages/knex-scripts/src/check-structure.ts
- packages/knex-scripts/src/cli.ts
- packages/knex-scripts/src/config.ts
- packages/knex-scripts/src/create.ts
- packages/knex-scripts/src/drop.ts
- packages/knex-scripts/src/dump.ts
- packages/knex-scripts/src/load.ts
- packages/knex-scripts/src/truncate.ts
- packages/knex-scripts/src/utils.ts
- packages/knex-scripts/tsconfig.json
- pnpm-lock.yaml
The package we used was outdated and unmaitained. We had some security
issues because of it.
> chore: move knex-scripts to a local package

- apps/frontend/src/router.tsx
> fix: fix dynamic import loading error detection

- apps/backend/src/github/auth.ts
> chore: add logs to understand GitHub OAuth failure

- apps/frontend/src/pages/Project/Builds.tsx
> fix(builds): fix page fetching

- apps/backend/db/migrations/20250103131406_plan-interval.js
- apps/backend/db/structure.sql
- apps/backend/src/database/models/Account.ts
- apps/backend/src/database/models/Plan.ts
- apps/backend/src/database/models/Subscription.e2e.test.ts
- apps/backend/src/database/models/Subscription.ts
- apps/backend/src/database/seeds.ts
- apps/backend/src/database/testing/factory.ts
- apps/frontend/src/containers/PlanCard.tsx
Support year interval for plans. In this case the "includedScreenshots" is annual (also the includedScreenshots on the subscriptions table).
> support year interval

- apps/backend/src/database/models/Build.ts
> fix(build): fix inconsistent status

- apps/backend/src/graphql/services/project.ts
> fix(project): fix project deletion

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/ui/ImageKitPicture.tsx
- apps/frontend/src/util/color-detection/hook.ts
- apps/frontend/src/util/color-detection/worker.ts
- **fix(images): fix imagekit parameters**
- **chore: capture worker exceptions in Sentry**
> fix image kit parameters

- apps/backend/src/graphql/definitions/Team.ts
> fix: support invalid team invitation token

- apps/frontend/src/pages/Build/BuildParams.ts
> fix: validate signed integer

- apps/frontend/src/ui/Charts.tsx
Description: Fix pie chart responsive
**Before**
**After**
> feat(analytics): fix pie chart responsive

- apps/backend/src/graphql/definitions/User.ts
> fix: handle 401 from GitHub

- apps/frontend/src/pages/Build/BuildDetailToolbar.tsx
> fix: fix `URL.canParse` not available

- apps/frontend/src/containers/AccountHistory.tsx
- apps/frontend/src/containers/ColorMode.tsx
- apps/frontend/src/containers/Project/ConnectRepository.tsx
- apps/frontend/src/util/oauth.ts
- apps/frontend/src/util/security-error.ts
- apps/frontend/src/util/storage.ts
- apps/frontend/src/util/useStorageState.ts
> fix(local-storage): build a safe abstraction

- apps/backend/src/synchronize/synchronizer.ts
> fix: handle bad credentials error

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/ui/useResizeObserver.ts
- apps/frontend/src/util/color-detection/hook.ts
- **fix: ensure diff indicator is always in sync**
- **feat: ensure minimum diff indicator size is one scren pixel**
- **refactor: optimize diff indicator code**
> improve diff indicator

- apps/frontend/src/util/search-params.ts
> fix: fix intersection not available

- .vscode/settings.json
- apps/backend/src/web/app-router.ts
- **chore(vscode): set Prettier as default formatter**
- **fix: set security headers on /graphql**
> fix security issues

- apps/backend/src/web/middlewares/resend.ts
> Fix resend error

- apps/frontend/src/util/color-detection/worker.ts
> fix: gracefully fail if no OffscreenCanvas

- apps/backend/package.json
- knip.json
- package.json
- pnpm-lock.yaml
Fix https://github.com/argos-ci/argos/security/dependabot/219
> fix(security): fix formidable security issue

- apps/backend/src/synchronize/github/eventHelpers.ts
> fix: fix GitHub installation handling

- apps/frontend/src/pages/Build/BuildInfos.tsx
In build infos the icon was wrong.
> fix: fix icon for failed build

- apps/backend/src/build/partial.ts
> fix: fix partial build support for light app

- apps/backend/src/database/models/Account.ts
- apps/backend/src/database/models/Build.ts
- apps/backend/src/database/models/BuildShard.ts
- apps/backend/src/database/models/GoogleUser.ts
- apps/backend/src/database/models/Project.ts
- apps/backend/src/database/models/Screenshot.ts
- apps/backend/src/database/models/Subscription.ts
- apps/backend/src/database/models/User.ts
- apps/backend/src/database/schemas/ScreenshotMetadata.ts
> fix: fix JSON schema

- apps/backend/src/api/handlers/createBuild.ts
- apps/backend/src/build/createBuild.ts
While investigating why our db becomes very slow.
> fix: increase lock timeout in the meantime

- apps/frontend/src/pages/Automation/AutomationTestNotification.tsx
- apps/frontend/src/pages/Automation/EditAutomation.tsx
- apps/frontend/src/pages/Automation/NewAutomation.tsx
> feat(automations): update submit button order

- apps/backend/src/automation/actions/sendSlackMessage.ts
- apps/backend/src/slack/buildStatusMessage.ts
> feat(automations): add test message disclaimer

- apps/backend/src/database/models/SlackInstallation.ts
- apps/backend/src/slack/index.ts
- apps/frontend/src/containers/Team/Slack.tsx
feat(slack): handle Slack permissions in automation
> Update slack section

- apps/backend/src/graphql/services/project.e2e.test.ts
- apps/backend/src/graphql/services/project.ts
- apps/backend/src/metrics/test.e2e.test.ts
> fix: fix project deletion

- .github/workflows/ci.yml
- CONTRIBUTING.md
- apps/backend/db/structure.sql
- docker-compose.yml
Commands to upgrade PG locally
```bash
brew install postgresql@17
brew unlink postgresql@14
brew link postgresql@17 --force
```
> chore: upgrade to pg v17

- apps/backend/src/build/strategy/strategies/ci/index.ts
> Revert "fix: always trust commit specified by user"

- package.json
- pnpm-lock.yaml
> Revert "fix: fix security issue with brace-expansion"

- apps/frontend/src/containers/Project/ConnectRepository.tsx
- apps/frontend/src/containers/Team/Members.tsx
- **fix: show an error boundary if an error occurs while loading repo**
- **fix: avoid reloading page when we click "Load more"**
> Various fixes for settings

- apps/frontend/src/index.css
- apps/frontend/src/pages/Build/BuildDiffList.tsx
- apps/frontend/src/pages/Build/BuildReviewDialog.tsx
- apps/frontend/src/pages/Build/TrackButtons.tsx
- apps/frontend/src/ui/Modal.tsx
- **fix: fix bad build review dialog**
- **fix: fix hover card visibile on dialog screen**
Fix #1736
> 1736 bug with dialog state

- apps/backend/src/graphql/definitions/Build.ts
> feat: sort changes by score desc

- apps/backend/src/web/middlewares/tokenless-strategies/github-actions.ts
> fix(tokenless): allow "queued" jobs for tokenless

- apps/frontend/src/router.tsx
Should also solve flaky visual tests
> fix: add real hydrate fallback

- apps/backend/src/database/models/GithubPullRequest.ts
- apps/backend/src/github-pull-request/pull-request.ts
- packages/util/src/string.test.ts
- packages/util/src/string.ts
Fix ARGOS-SERVER-Y72
Fix ARGOS-SERVER-Y71
> fix(pull-request): fix max PR title

- apps/backend/src/database/services/account.ts
> fix: fix linking GitHub account

- apps/frontend/src/pages/Project/BuildNameFilter.tsx
- apps/frontend/src/ui/TextInput.tsx
> feat: build names autocomplete

- apps/frontend/src/containers/Team/Members.tsx
> fix(settings): fix members layout

- apps/backend/src/sentry/index.ts
> chore: set level of info for 4xx errors

- apps/frontend/src/containers/Layout.tsx
- apps/frontend/src/containers/NavUserControl.tsx
- apps/frontend/src/pages/Account/Settings.tsx
- apps/frontend/src/pages/Account/index.tsx
- apps/frontend/src/pages/Automation/EditAutomation.tsx
- apps/frontend/src/pages/Automation/NewAutomation.tsx
- apps/frontend/src/pages/Project/GettingStarted.tsx
- apps/frontend/src/pages/Project/Settings.tsx
- apps/frontend/src/pages/Project/index.tsx
- apps/frontend/src/router.tsx
- apps/frontend/src/ui/Nav.tsx
- apps/frontend/src/ui/TabLink.tsx
https://github.com/user-attachments/assets/4eeb9550-69f2-479c-9279-3e02be9db4c5
> feat(settings): split in several pages

- apps/backend/src/database/services/account.ts
> fix(auth): fix auth with third party

- apps/frontend/src/containers/Build/BuildHotkeys.tsx
- apps/frontend/src/ui/Modal.tsx
> fix(hotkey): ignore hotkeys in modal

- package.json
- pnpm-workspace.yaml
https://pnpm.io/blog/releases/10.16
> chore(security): add minimum release age before installing npm packages

- apps/backend/src/api/handlers/createBuild.ts
> fix(api): fix commit validation

- apps/frontend/src/util/oauth.ts
Fix ARGOS-BROWSER-DA
Fix ARGOS-BROWSER-DB
> fix(oauth): fallback to cookie if storage not available

- apps/backend/src/gitlab/client.ts
- apps/backend/src/notification/handlers/index.ts
- apps/backend/src/notification/handlers/invalid_gitlab_token.tsx
Also notify if token is invalid
Fix ARGOS-SERVER-Y7W
> fix(gitlab): handle invalid token error

- apps/backend/src/graphql/services/github.ts
- apps/frontend/src/containers/Project/GitRepository.tsx
> fix: handle repo not found error
