- package.json
```sh
Sorry an error happened:
request to http://api.argos-ci.com/builds failed, reason: getaddrinfo ENOTFOUND api.argos-ci.com api.argos-ci.com:80
```
> fix: do not block if argos fails

- .gitignore
- examples/docker-compose.yml
- examples/with-wdio/.eslintrc.js
- examples/with-wdio/README.md
- examples/with-wdio/config.js
- examples/with-wdio/package.json
- examples/with-wdio/test/wdio-screenshot.js
- examples/with-wdio/test/wdio-visual-regression-service.js
- examples/with-wdio/wdio.conf.js
Used https://github.com/algolia/instantsearch.js/pull/2166 as starting point.
```sh
01:56:36 {with-wdio} ~/argos/examples/with-wdio$ yarn test
yarn test v0.21.3
$ wdio
․․․․
4 passing (61.20s)
✨  Done in 63.69s.
```
Next example: **vrtest** cc @nathanmarks 😄
> feat: finish with-wdio

- .gitignore
- examples/with-vrtest/.eslintrc.js
- examples/with-vrtest/.gitignore
- examples/with-vrtest/README.md
- examples/with-vrtest/components/angular/Button.js
- examples/with-vrtest/components/react/Button.js
- examples/with-vrtest/components/vue/Button.vue
- examples/with-vrtest/package.json
- examples/with-vrtest/test/.babelrc
- examples/with-vrtest/test/debug.html
- examples/with-vrtest/test/index.js
- examples/with-vrtest/test/webpack.config.js
- examples/with-vrtest/vrtest.conf.js
- examples/with-wdio/.gitignore
Use [vrtest](https://github.com/nathanmarks/vrtest) of @nathanmarks.
Input a component (React or Angular and Vue). For instance:
```jsx
import React from 'react'
const style = {
background: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
borderRadius: 3,
border: 0,
color: 'white',
height: 48,
padding: '0 30px',
boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .30)',
}
function Button() {
return (
<button type="button" style={style}>
{'vrtest'}
</button>
)
}
export default Button
```
Output a screenshots:
For instance:
> examples(vrtest): add a new integration example

- src/server/routes/api.js
`batchCount` may be a string if it was fetched from a system env.
This resulted in forever pending builds because of the strict comparison made with the actual batchCount in db.
I hesitated for a while about directly casting the value in the cli instead. Wasn't too sure. What do you think? @neoziro  
It would be cleaner from a server standpoint, but not too sure we can trust to client, since it may not always be the argos-cli.
> fix(batch): Cast batchCount String to Int before comparison

- src/server/routes/api.js
Some Argos builds were forever pending because of a race condition in the way we incremented the batch counter.
There was a quick time gap between the fetching of the current batchCount and the update of the column.
> Fix race condition when incrementing batchCount

- apps/app/src/pages/Repository/BuildDetail/Screenshots.js
Hi Greg,
On our builds for Doctolib, we now have something like 3k screenshots and the page takes a while to load. Some of the time is spent waiting for the server payload to arrive but it seems there is also quite some time spent client side building the UI once the payload has arrived. The loading animation actually freezes on my computer. This PR hopes to alleviate that by hiding passing screenshots by default (while still providing a link to toggle them). In my experience using Argos, passing screenshots are rarely useful, that would be one extra click for the rare cases when you need them.
What do you think?
> Hide passing screenshots by default

- apps/logger/src/index.js
I need to monitor production errors on Sentry. The previous logger hides the errors.
@gregberge can you confirm if that's a good fix?
> feat: logger throws prod errors

- apps/web/package.json
- apps/web/src/authorizations/bearerAuth.js
- apps/web/src/authorizations/bearerAuth.test.js
- apps/web/src/authorizations/repoAuth.js
- apps/web/src/authorizations/repoAuth.test.js
- package-lock.json
These middlewares will be used in the new upload API to handle authorization from the repository token.
> chore: add middlewares to auth as repo

- apps/app/src/components/ProgressBar.js
- apps/app/src/components/Theme.js
- apps/app/src/pages/Build/SummaryCard.js
- apps/app/src/pages/Owner/GeneralSettings.js
I took some screenshots to help review
> feat(build): use progress bar as pregression indicator

- apps/graphql/src/definitions/Build.ts
- apps/graphql/src/definitions/ScreenshotDiff.ts
- apps/screenshot-diff/src/computeScreenshotDiff.ts
We forgot to patch the score when there are only negligible diffs. This mistake create a new type of diff with filled baseScreenshotId, filled compareScreenshotId but without score.
First, I have fixed our mistake. Then, I have updated the screenshot diff status algo: 
- No compareScreenshotId => "removed"
- No baseScreenshotId + "failed" in name => "failed"
- No baseScreenshotId => "added"
- score && score > 0 => "updated"
- else => "stable"
> fix: fix screenshot diff status

- apps/synchronize/src/github/synchronizer.ts
When we synchronize an installation we synchronize all users. But we
synchronize them in parallel, however the `this.octokit` is shared. It
means we obtain a wrong `octokit` for a dedicated user.
To fix the problem we add a synchronization job that will be
independent.
> fix(synchronizer): fix synchronize from installation

- apps/web/src/api/v2/builds/create.ts
We increase the signed URL validity duration to 30 minutes. The upload of screenshots could be significantly longer than 3 minutes. Also it is not a security problem to authorize it for 30 minutes.
> fix(argos): increase signed URL validity duration

- apps/build-notification/src/notifications.ts
- apps/database/src/models/Build.test.ts
- apps/database/src/models/Build.ts
- apps/github/src/client.ts
$fetchGraph resets other fields
> refactor: make `Build.getUrl` safe

- apps/build-notification/src/notifications.ts
When a diff is detected we should put it in failure instead of pending.
Pending means: it is not finished, I am awaiting for something.
Actually the Argos build is finished and an error has been detected.
It was the original behaviour of Argos and it was better.
> feat(build): put GitHub status in failure on diff

- apps/database/src/models/Account.ts
When there is a `forcedPlan` we don't want to show anything about an active purchase.
> fix: no active purchase for forcedPlan

- apps/app/src/pages/Build/BuildHotkeys.tsx
Hotkeys are without the modifier key. It means CMD + Number will not
override switching to browser tabs.
> fix(hotkeys): fix hotkey modifier

- apps/web/src/middlewares/tokenless-strategies/github-actions.ts
> fix(tokenless): use HTTP 400 for multiple repo

- apps/app/src/containers/Breadcrumb/AccountBreadcrumbMenu.tsx
- apps/app/src/containers/NavUserControl.tsx
- apps/app/src/containers/PlanCard.tsx
- apps/app/src/pages/Account/Settings.tsx
Our tunnel is confusing. I've added an "Add Member" button to personal settings. This button opens a modal explaining that collaboration is only possible within a team setting.
- feat: update create team icon
- feat: add collaboration-warning-dialog
Fix [#1044](https://github.com/argos-ci/argos/issues/1044)
> collaboration warning dialog

- apps/backend/src/build-notification/notifications.ts
To avoid secondary rate limit, following guidelines https://docs.github.com/en/rest/guides/best-practices-for-using-the-rest-api\?apiVersion\=2022-11-28\#dealing-with-secondary-rate-limits
Fix ARGOS-SERVER-XJX
Fix ARGOS-SERVER-XJT
Fix ARGOS-SERVER-XJV
> fix(github): call API serially

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/Zoomer.tsx
- playwright.config.mjs
Firefox has a bug measuring the content of a "relative" div. It does not give the size of its children. To fix this problem we size correctly the parent div.
**Before**
**After**
> fix(firefox): fix diff display on Firefox

- apps/frontend/src/pages/Build/BuildDetail.tsx
Fix the build diff display on Safari.
**Before**
**After**
> fix: fix build diff display on Safari

- apps/backend/src/screenshot-diff/util/image-diff/index.ts
- apps/backend/src/screenshot-diff/util/image-diff/test/diff.test.ts
As observed, sometimes dynos are out of memory. We try to mitigate this
by running diffs sequentially instead of in parallel.
> perf: run diffs sequentially

- apps/backend/src/stripe/index.ts
- apps/backend/src/web/api/stripe.ts
So no need to listen the event anymore
Also add event to the context for quicker debugging
Fix ARGOS-SERVER-XMX
> fix(stripe): payment method can't be detached

- apps/backend/src/util/redis/lock.e2e.test.ts
- apps/backend/src/util/redis/lock.ts
To be more reactive if already locked and avoid concurrency issues
> perf: adjust lock retry delay

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/Zoomer.tsx
- apps/frontend/src/util/color-detection/hook.ts
- apps/frontend/src/util/color-detection/types.ts
- apps/frontend/src/util/color-detection/worker.ts
- knip.json
We compute the groups of differences on the fly by analyzing the image in an [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) in a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). This way the main thread is not blocked during the computation of diff rects.
Once done, we display a lateral bar by getting the initial scale of the image and subscribing to the zoom level.
> feat: diff indicator

- apps/backend/src/api/util.ts
E2E test [Failed again](https://github.com/mermaid-js/mermaid/actions/runs/11161194204/job/31023256387). 
I am not sure what the actual size we sent is. 
In case you have logs with this info, please update the size. 
Based on #1380
> fix: increase api limit

- apps/backend/src/auth/request.ts
- apps/backend/src/graphql/context.ts
- apps/backend/src/web/middlewares/auth.ts
- apps/backend/src/web/util.ts
- No error if used as middleware
- In GraphQL throws error only if the user or if the JWT is invalid
(ignore invalid scheme)
Fix ARGOS-SERVER-XQ3
Fix ARGOS-SERVER-XQC
Fix ARGOS-SERVER-XQD
> fix: fix auth error handling

- apps/backend/src/graphql/definitions/Screenshot.ts
- apps/backend/src/graphql/definitions/ScreenshotDiff.ts
- apps/backend/src/slack/index.ts
- apps/backend/src/storage/public-url.ts
- apps/frontend/src/ui/TwicPicture.tsx
Twipics has a limit of 36M pixels for an image.
So for image bigger than that we directly use S3 to display it.
> fix: support big images

- apps/backend/src/web/app-router.ts
> fix(google-auth): redirect if query params are invalid

- apps/frontend/src/pages/AuthCallback.tsx
> chore: ignore "invalid_grant" error in Sentry

- apps/backend/db/migrations/20250103090503_remove-validation-status-column.js
- apps/backend/db/structure.sql
- apps/backend/src/build/createBuildDiffs.e2e.test.ts
- apps/backend/src/build/createBuildDiffs.ts
- apps/backend/src/build/job.e2e.test.ts
- apps/backend/src/database/models/ScreenshotDiff.test.ts
- apps/backend/src/database/models/ScreenshotDiff.ts
- apps/backend/src/database/seeds.ts
- apps/backend/src/database/testing/factory.ts
- apps/backend/src/graphql/definitions/Build.ts
- apps/backend/src/screenshot-diff/computeScreenshotDiff.e2e.test.ts
We now rely on build_reviews table only.
> refactor: remove `validationStatus` from screenshot_diffs table

- apps/frontend/src/util/color-detection/hook.ts
- apps/frontend/src/util/color-detection/types.ts
- apps/frontend/src/util/color-detection/worker.ts
ImageKit supports 100M pixels and our limit is 80M in the API so all images should be in jpg now and the problem is solved. It's a fix only for old builds.
Fix ARGOS-BROWSER-B8
> fix: avoid processing non-jpg images in worker

- apps/backend/src/graphql/definitions/Project.ts
In order to avoid user clicking on it after a timeout.
Fix ARGOS-SERVER-XRN
> fix: make `deleteProject` idempotent

- apps/frontend/src/pages/Build/BuildDetailToolbar.tsx
- apps/frontend/src/util/url.ts
> fix: fix support for `URL.canParse` not available

- apps/frontend/src/pages/Build/BuildDetail.tsx
- apps/frontend/src/pages/Build/Zoomer.tsx
The min and max scaling is now consistent whatever the initial size of the image.
> fix: ensure scaling is consistent whatever contained mode or not

- apps/frontend/src/util/oauth.ts
- apps/frontend/src/util/storage.ts
Throw if localStorage is disabled, we need it to store nonce.
Fix ARGOS-BROWSER-AW
> fix: fix OAuth state

- apps/backend/src/screenshot-diff/computeScreenshotDiff.ts
It may overload database, we have unexplained errors on the build creation
> chore: temporary disable upsert

- apps/backend/src/build/concludeBuild.ts
- apps/backend/src/build/job.e2e.test.ts
- apps/backend/src/build/partial.ts
- apps/backend/src/graphql/tests/setValidationStatus.e2e.test.ts
- apps/backend/src/job-core/createJob.ts
- apps/backend/src/screenshot-diff/computeScreenshotDiff.ts
- apps/backend/src/screenshot-diff/job.ts
- **refactor: run compute build in a lock**
- **refactor: allow to specify a custom timeout for a job**
- **refactor: set the screenshot diff job timeout to 30s**
- **perf: optimize computeScreenshotDiff for grouping**
- **fix(build): avoid being dependant on GitHub**
> Various fixes
